name: "Tesseract API"
version: "0.3.5"
slug: "tesseract"
description: "Tesseract web API"
arch: [
  "armhf",
  "armv7",
  "aarch64",
  "amd64",
  "i386"
]
startup: "before"
boot: "auto"
ports:
  "5000/tcp": 5000

